/**
 * wordSheet.js — The word detail sheet.
 *
 * Opened from an AR label, a detected card, or the vocabulary list. Shows the
 * target word with its gender and phonetics, generated example sentences, the
 * learner's own history with the word, and every other language side by side.
 */

import { DICT, translate, CATEGORIES } from '../data/dictionary.js';
import { LANGUAGES, LANG_CODES, PHRASE_LABELS, buildPhrase, genderLabel, citationForm } from '../data/languages.js';
import { state, wordRecord } from '../core/store.js';
import { masteryLevel, formatDue } from '../core/srs.js';
import { speak, hasVoice } from '../core/speech.js';
import { openSheet, esc, $$, relativeDay } from '../ui/kit.js';
import { icon } from '../ui/icons.js';
import { cue } from '../core/feedback.js';

export function openWordSheet(cls) {
  const entry = DICT[cls];
  if (!entry) return;
  const lang = state.settings.targetLang;
  const t = translate(cls, lang);
  if (!t) return;

  const rec = wordRecord(cls, lang);
  const gTag = genderLabel(lang, t.gender);
  const cat = CATEGORIES[entry.cat];
  const voiceOk = hasVoice(lang);

  const body = openSheet({ title: '' });
  body.innerHTML = renderSheet({ cls, entry, t, gTag, cat, rec, lang, voiceOk });

  // Speak buttons — each carries the text and language it should pronounce.
  $$('[data-speak]', body).forEach((btn) => {
    btn.addEventListener('click', () => {
      cue('tap', 'light');
      speak(btn.dataset.speak, btn.dataset.lang || lang);
    });
  });
}

function renderSheet({ cls, entry, t, gTag, cat, rec, lang, voiceOk }) {
  const citation = citationForm(lang, t.word, t.gender);

  const hero = `
    <div class="word-hero">
      <div class="em">${esc(entry.em)}</div>
      <div class="grow">
        <div class="foreign">${esc(t.word)}</div>
        <div class="english">${esc(cls)}</div>
        ${state.settings.showPhonetics && t.phonetic ? `<div class="phon">${esc(t.phonetic)}</div>` : ''}
      </div>
      <button class="icon-btn icon-btn-lg" data-speak="${esc(citation)}" data-lang="${lang}"
              aria-label="Pronounce ${esc(t.word)}" ${voiceOk ? '' : 'disabled title="No voice installed for this language"'}>
        ${icon('speaker')}
      </button>
    </div>`;

  const tags = `
    <div class="row wrap gap-2" style="margin-bottom:var(--s-5)">
      ${gTag ? `<span class="gender-tag">${esc(gTag)}</span>` : ''}
      <span class="chip">${esc(cat.em)} ${esc(cat.label)}</span>
      <span class="chip">Level ${entry.lvl}</span>
      ${rec ? `<span class="chip">Seen ${rec.seen}×</span>` : '<span class="chip">Not yet spotted</span>'}
    </div>`;

  /* Example sentences, generated by the grammar engine rather than stored.
     "How much is the person?" is nonsense, so animate nouns skip that frame. */
  const animate = entry.cat === 'people' || entry.cat === 'animal';
  const frames = Object.keys(PHRASE_LABELS).filter((f) => !(animate && f === 'how_much'));

  const phrases = frames.map((frame) => {
    const sentence = buildPhrase(lang, t.word, t.gender, frame);
    return `
      <div class="phrase-row">
        <div class="body">
          <div class="target">${esc(sentence)}</div>
          <div class="gloss">${esc(PHRASE_LABELS[frame].replace('…', cls))}</div>
        </div>
        <button class="icon-btn" data-speak="${esc(sentence)}" data-lang="${lang}"
                aria-label="Play sentence" ${voiceOk ? '' : 'disabled'}>${icon('speaker')}</button>
      </div>`;
  }).join('');

  const progress = rec ? `
    <div class="section-label">Your progress</div>
    <div class="group" style="margin-bottom:var(--s-5)">
      <div class="list-row">
        <div class="list-row-body"><div class="list-row-title">Mastery</div></div>
        <div class="mastery">${[1, 2, 3, 4, 5].map((i) =>
          `<i class="${i <= masteryLevel(rec) ? 'on' : ''}"></i>`).join('')}</div>
      </div>
      <div class="list-row">
        <div class="list-row-body"><div class="list-row-title">Next review</div></div>
        <div class="list-row-value">${rec.srs.reps ? esc(formatDue(rec.srs.due)) : 'not started'}</div>
      </div>
      <div class="list-row">
        <div class="list-row-body"><div class="list-row-title">Accuracy</div></div>
        <div class="list-row-value">${rec.correct + rec.wrong
          ? Math.round(rec.correct / (rec.correct + rec.wrong) * 100) + '%'
          : '—'}</div>
      </div>
      <div class="list-row">
        <div class="list-row-body"><div class="list-row-title">First spotted</div></div>
        <div class="list-row-value">${esc(relativeDay(rec.discoveredAt))}</div>
      </div>
    </div>` : '';

  /* Every other language, so the sheet doubles as a mini phrasebook. */
  const others = LANG_CODES.filter((l) => l !== lang).map((l) => {
    const o = translate(cls, l);
    if (!o) return '';
    const meta = LANGUAGES[l];
    const g = genderLabel(l, o.gender);
    return `
      <button class="list-row is-tappable" data-speak="${esc(citationForm(l, o.word, o.gender))}" data-lang="${l}">
        <div class="list-row-icon" style="background:transparent;font-size:20px">${esc(meta.flag)}</div>
        <div class="list-row-body">
          <div class="list-row-title" ${meta.rtl ? 'dir="rtl"' : ''}>${esc(o.word)}
            ${g ? `<span class="gender-tag" style="margin-left:6px">${esc(g)}</span>` : ''}</div>
          <div class="list-row-sub">${esc(meta.name)}${o.phonetic ? ' · ' + esc(o.phonetic) : ''}</div>
        </div>
        <div class="list-row-chevron">${icon('speaker')}</div>
      </button>`;
  }).join('');

  return `
    ${hero}
    ${tags}
    ${!voiceOk ? `<p class="footnote" style="margin-bottom:var(--s-4)">
      ${icon('info')} No ${esc(LANGUAGES[lang].name)} speech voice is installed on this device — text is still shown.
    </p>` : ''}
    <div class="section-label">Use it in a sentence</div>
    <div class="group" style="margin-bottom:var(--s-5)">${phrases}</div>
    ${progress}
    <div class="section-label">In other languages</div>
    <div class="group">${others}</div>
    <div style="height:var(--s-4)"></div>`;
}
